#!/usr/bin/env python
"""
================================================================================
MANAGE.PY - DJANGO COMMAND-LINE UTILITY
================================================================================

This is Django's command-line interface (CLI) tool.
You use this to run the development server, create database tables, etc.

Think of it as: "The Swiss Army knife of Django development"

COMMON COMMANDS:
    python manage.py runserver              # Start development server
    python manage.py makemigrations         # Detect model changes
    python manage.py migrate                # Apply database changes
    python manage.py createsuperuser        # Create admin user
    python manage.py shell                  # Open Python shell with Django loaded
    
DO NOT EDIT THIS FILE! It's auto-generated by Django.
================================================================================
"""
import os
import sys


def main():
    """Run administrative tasks."""
    # Tell Django where to find settings
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
    
    try:
        # Import Django's command runner
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    
    # Execute the command from sys.argv
    # Example: If you run "python manage.py runserver"
    # sys.argv = ['manage.py', 'runserver']
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
