# Generated by Django 6.0 on 2026-02-03 08:43

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='url',
            field=models.CharField(help_text='The endpoint where we send the webhook', max_length=500, validators=[delivery.models.FlexibleURLValidator()]),
        ),
    ]
